version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: bookhood-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: Aa123456
      POSTGRES_DB: bookhood
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: